### ISSUE TITLE
ini vs. inifile

### ISSUE THREAD

**Issue by ghost** [TwP/inifile#1]
I noticed on Gemcutter there are two gems, ini and inifile. The ini gem appears to be a copy of inifile, but renamed. Tim, you are listed as an author on both. Do you control that gem too? Or is that under Rob Muhlestein's control? Considering they are essentially the same, but inifile is a little further along, it would be nice to see the two projects reunify --and IMHO under the more succinct 'ini' name.

**Comment by TwP** [comment]
That is under Rob Muhlestein's control. There was talk of merging / working together on these gems. Nothing much came of it, though. And yes, "ini" is a much more succinct name - not much I can do about that :-/
