### ISSUE TITLE
Lack of newline at end of file causes error

### ISSUE THREAD

**Issue by jm** [TwP/inifile#12]
If you have an ini file without a newline at the end of the file, it will fail to parse with a `Could not parse line` error.  Example file:

```
[my_section]
my_property = And now I die.
```

**Comment by jm** [comment]
Simple fix is to just add a `\n` to `@content`.  If that works for you, then I'll PR it.

**Comment by TwP** [comment]
Just pushed a new release (v 2.0.2) with the patch from @erebor.
