### ISSUE TITLE
Be able to use value outside a section

### ISSUE THREAD

**Issue by guilhem** [TwP/inifile#30]
Ini files can be quite bad and different.
Sometimes, values are alone before any section.
https://github.com/datafolklabs/ruby-parseconfig , for example, manage this case:

``` ini
# Example Config
param1 = value1
param2 = value2

[group1]
group1_param1 = group1_value1
group1_param2 = group1_value2

[group2]
group2_param1 = group2_value1
group2_param2 = group2_value2
```

I wrote a commit some times ago: https://github.com/optiflows/inifile/commit/c037bff0edd1ff917d9b69fcdf69a8028d2a331f

But it's only a way to do. there may be other.

**Comment by guilhem** [comment]
This commit was based on #20 but as it wasn't merged, isn't applicable as it.

**Comment by TwP** [comment]
There is a default `global` section where top-level values are stored. You can change the name of this global section by passing in a `:default` value when creating an IniFile instance.

``` ruby
inifile = IniFile.new(:filename => 'mine.ini', :default => 'top-level-section')
```

**Comment by fwolfst** [comment]
@guilhem So, access your values like

``` ruby
inifile[:global]["param1"] # value1
```

**Comment by TwP** [comment]
@fwolfst perfect! `:global` is the default top-level section where values are stored. I forgot to mention that :blush:

**Comment by guilhem** [comment]
Thanks you two!
I'm quite old with this issue. I will give another look to my needs ;)
