### ISSUE TITLE
rubygems.org entry does not show "Source Code" link

### ISSUE THREAD

**Issue by fwolfst** [TwP/inifile#32]
Thanks for this gem.
The rubygems.org page does not list the github repo as "Homepage" nor as "Source Code" link. Later apparently can only be set via the rubygems.org page after a login. Would be nice if you specify it.

**Comment by fwolfst** [comment]
Man I want to be able to specify this in the gemspec, opened an issue for it (rubygems/rubygems#1007).

**Comment by TwP** [comment]
Added a link to the source code. :bow:

**Comment by fwolfst** [comment]
Great, thanks!
