### ISSUE TITLE
for loop in .ini file

### ISSUE THREAD

**Issue by mahtaparsa** [TwP/inifile#46]
Hi everybody,
Is it possible to define a for loop in a .ini file?
For example we have for loop in C or Python,...
Can we define such loops in .ini file?

**Comment by letarg0** [comment]
Yes,
`myini.each_section do |section_desc| `  change section_desc to 'my_section'

if You dont know what is inside object just print it
`p myini`

**Comment by hussaintamboli** [comment]
Can you put an example? It's not clear from this discussion. Thanks.

**Comment by mahtaparsa** [comment]
The problem have been solved. Thanks for your replies.
